# Generated by Django 3.2.3 on 2021-05-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='Book_info',
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='Book_Category',
            field=models.CharField(default=121, max_length=150, verbose_name='Book Category '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='Book_Author',
            field=models.ForeignKey(default=212, on_delete=django.db.models.deletion.CASCADE, to='backend.bookauthor', verbose_name='Book Author Name '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='Book_Category',
            field=models.ForeignKey(default=2121, on_delete=django.db.models.deletion.CASCADE, to='backend.bookcategory', verbose_name='Book Category Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='Book_Name',
            field=models.ForeignKey(default=2121, on_delete=django.db.models.deletion.CASCADE, to='backend.bookadd', verbose_name='Book Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='Book_Author',
            field=models.CharField(max_length=200, verbose_name='Book Authors Name '),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='Book_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bookadd', verbose_name='Books Name'),
        ),
    ]
