# Generated by Django 3.2.3 on 2021-05-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcode',
            name='Book_Ifsc',
            field=models.CharField(max_length=13, verbose_name='Book Ifsc Number'),
        ),
    ]
