# Generated by Django 3.2.3 on 2021-05-16 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Mob_Number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that Phone Number address already exists'}, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Phone Number '),
        ),
    ]
