# Generated by Django 3.2.3 on 2021-05-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210517_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='Book_Isbn',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='Book_Publication',
        ),
    ]
